### ISSUE TITLE
Dokumentálás

### ISSUE THREAD

**Issue by FractalXX** [FractalXX/KeyWarrior#22]
- [x] Funkcionális specifikáció
- [x] Rendszerterv
- [x] Árajánlat
- [x] Tesztelési terv
- [x] Ajánlat
- [x] Ajánlat kérés

**Comment by Knekochan** [comment]
Árajánlat
Becsült idő: 5-7 óra
Ráfordított idő: 8 óra

**Comment by bbalazs79** [comment]
Funkcionális Specifikáció
Becsült idő: 3-5 óra

**Comment by bbalazs79** [comment]
Eddig ráfordított idő: 3óra
Becsült időtartam a további kidolgozásra: 2-3 óra

**Comment by bbalazs79** [comment]
Eddig ráfordított idő: 3óra 
Jelenlegi ráfordított idő: 2óra
Összesítve: 5óra munkaidő

**Comment by bbalazs79** [comment]
Funkcionális specifikációra és Követelmény specifikáció javítására illetve bővítésére fordított további időtartam: 45perc
Összesítve: 5óra 45perc

**Comment by bbalazs79** [comment]
Ajánlat: Becsült idő: 1 óra
Ráfordított idő 2 óra

**Comment by FractalXX** [comment]
Rendszerterv becsült idő: **10 óra**
Ráfordított idő: 6 óra

**Comment by Knekochan** [comment]
Tesztelési terv
Becsült idő: 3 óra
Ráfordított idő: 2 óra

**Comment by bbalazs79** [comment]
Ajánlat kérés 
Becsült időtartam: 1 óra
Munkaidő: 1 óra
