### ISSUE TITLE
Béta teszt

### ISSUE THREAD

**Issue by FractalXX** [FractalXX/KeyWarrior#46]
A teszt elsődleges célja: Minden meglévő funkció megfelelő működésének ellenőrzése.
A tesztet harmadik személyek végzik.

_Időtartam_: 4 nap.
_Teszt kezdete:_ **2017/12/08**
_Teszt befejezése:_ **2017/12/11**

**Comment by bbalazs79** [comment]
https://docs.google.com/spreadsheets/d/15feXCk8c5bpF-mRHFG8e4oyRXdJrbgycrvgKNOQZo88/edit#gid=0

**Comment by bbalazs79** [comment]
https://docs.google.com/spreadsheets/d/15feXCk8c5bpF-mRHFG8e4oyRXdJrbgycrvgKNOQZo88/edit?usp=sharing
